# Generated by Django 4.2.6 on 2023-10-05 01:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CARRO', 'CARRO'), ('MOTO', 'MOTO'), ('CAMINHÃO', 'CAMINHÃO')], max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='categoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valorMaoDeObra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=12)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('automovelFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutençãoAutomovel', to='main.automovel')),
                ('funcionarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutençãoFuncionario', to='main.funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='postoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('QuantEstoque', models.IntegerField()),
                ('codigoFabricante', models.CharField(max_length=100)),
                ('nomeFabricante', models.CharField(max_length=100)),
                ('valorCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorVenda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('comentario', models.CharField(blank=True, max_length=400, null=True)),
                ('nota', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('clienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaCliente', to='main.clientes')),
                ('postoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaPosto', to='main.postotrabalho')),
            ],
        ),
        migrations.CreateModel(
            name='posto_funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postoFuncionario', to='main.funcionarios')),
                ('postoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posto', to='main.postotrabalho')),
            ],
        ),
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'BOLETO'), ('CC', 'CARTÃO DE CREDITO'), ('CD', 'CARTÃO DE DEBITO')], max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'APROVADO'), ('C', 'CANCELADO')], max_length=100)),
                ('valorDesconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorFinal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manutencaoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentoManutenção', to='main.manutencao')),
            ],
        ),
        migrations.CreateModel(
            name='manutencao_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutencaoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutençãoProduto', to='main.manutencao')),
                ('produtoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtoManutenção', to='main.produto')),
            ],
        ),
        migrations.CreateModel(
            name='mantencao_categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriaManutenção', to='main.categoriaservico')),
                ('manutencaoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutençãoCategoria', to='main.manutencao')),
            ],
        ),
        migrations.CreateModel(
            name='disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('postoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidadePosto', to='main.postotrabalho')),
                ('reservaFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidadeReserva', to='main.reserva')),
            ],
        ),
    ]
