# Generated by Django 4.2.6 on 2023-10-11 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_clientes_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='manutencaoFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservaManutenção', to='main.manutencao'),
        ),
    ]
